format_version: 10
pipelines:
  sample:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-84ee84a:
        git: https://github.com/frbk/gocd-test
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - asdasd:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          asdasds:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - '1'
                command: echo
                run_if: passed
